"""added_cascade_deleting

Revision ID: 1430975b881c
Revises: a513fc081f9f
Create Date: 2026-05-17 18:29:17.880438

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1430975b881c"
down_revision: Union[str, Sequence[str], None] = "a513fc081f9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("departments_department_id_fkey"), "departments", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "departments",
        "departments",
        ["department_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("employees_department_id_fkey"), "employees", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "employees", "departments", ["department_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "employees", type_="foreignkey")
    op.create_foreign_key(
        op.f("employees_department_id_fkey"),
        "employees",
        "departments",
        ["department_id"],
        ["id"],
    )
    op.drop_constraint(None, "departments", type_="foreignkey")
    op.create_foreign_key(
        op.f("departments_department_id_fkey"),
        "departments",
        "departments",
        ["department_id"],
        ["id"],
    )
    # ### end Alembic commands ###
