"""changed_name_field_departments

Revision ID: a513fc081f9f
Revises: 4bf3bd869f35
Create Date: 2026-05-17 10:21:53.181239

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a513fc081f9f"
down_revision: Union[str, Sequence[str], None] = "4bf3bd869f35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "departments", sa.Column("department_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(op.f("uq_department_parent_name"), "departments", type_="unique")
    op.create_unique_constraint(
        "uq_department_parent_name", "departments", ["department_id", "name"]
    )
    op.drop_constraint(
        op.f("departments_parent_id_fkey"), "departments", type_="foreignkey"
    )
    op.create_foreign_key(None, "departments", "departments", ["department_id"], ["id"])
    op.drop_column("departments", "parent_id")
    op.alter_column(
        "employees",
        "hired_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Date(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees",
        "hired_at",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.add_column(
        "departments",
        sa.Column("parent_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "departments", type_="foreignkey")
    op.create_foreign_key(
        op.f("departments_parent_id_fkey"),
        "departments",
        "departments",
        ["parent_id"],
        ["id"],
    )
    op.drop_constraint("uq_department_parent_name", "departments", type_="unique")
    op.create_unique_constraint(
        op.f("uq_department_parent_name"),
        "departments",
        ["parent_id", "name"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("departments", "department_id")
    # ### end Alembic commands ###
